######################################################################
# Automatically generated by qmake (2.01a) Sun Apr 20 18:12:55 2014
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += servo.h
SOURCES += main.cpp servo.cpp

CONFIG += console
